In [1]:
import pandas as pd
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
print("Train shape:", train.shape)
print("Test shape:", test.shape)
train.head()

Train shape: (8693, 14)
Test shape: (4277, 13)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [2]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   str
 1   HomePlanet    8492 non-null   str
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   str
 4   Destination   8511 non-null   str
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   str
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 891.5+ KB

In [ ]:
missing = train.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(train)) * 100
pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct.round(2)})

              Missing Count  Missing %
CryoSleep               217       2.50
ShoppingMall            208       2.39
VIP                     203       2.34
HomePlanet              201       2.31
Name                    200       2.30
Cabin                   199       2.29
VRDeck                  188       2.16
Spa                     183       2.11
FoodCourt               183       2.11
Destination             182       2.09
RoomService             181       2.08
Age                     179       2.06
PassengerId               0       0.00
Transported               0       0.00

In [4]:
train.groupby('CryoSleep')['Transported'].mean()

CryoSleep
False    0.328921
True     0.817583
Name: Transported, dtype: float64

In [5]:
train.groupby('CryoSleep')[['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']].mean()

           RoomService   FoodCourt  ShoppingMall        Spa      VRDeck
CryoSleep
False       350.146772  713.004316    270.586504  486.09294  475.716165
True          0.000000    0.000000      0.000000    0.00000    0.000000

In [6]:
train['Cabin'].head(10)

0    B/0/P
1    F/0/S
2    A/0/S
3    A/0/S
4    F/1/S
5    F/0/P
6    F/2/S
7    G/0/S
8    F/3/S
9    B/1/P
Name: Cabin, dtype: str

In [7]:
train[['Deck', 'CabinNum', 'Side']] = train['Cabin'].str.split('/', expand=True)
test[['Deck', 'CabinNum', 'Side']] = test['Cabin'].str.split('/', expand=True)
train[['Cabin', 'Deck', 'CabinNum', 'Side']].head()

   Cabin Deck CabinNum Side
0  B/0/P    B        0    P
1  F/0/S    F        0    S
2  A/0/S    A        0    S
3  A/0/S    A        0    S
4  F/1/S    F        1    S

In [8]:
print(train.groupby('Deck')['Transported'].mean().sort_values(ascending=False))
print()
print(train.groupby('Side')['Transported'].mean())

Deck
B    0.734275
C    0.680054
G    0.516217
A    0.496094
F    0.439871
D    0.433054
E    0.357306
T    0.200000
Name: Transported, dtype: float64

Side
P    0.451260
S    0.555037
Name: Transported, dtype: float64

In [9]:
print(train.groupby('HomePlanet')['Transported'].mean().sort_values(ascending=False))
print()
print(train.groupby('Destination')['Transported'].mean().sort_values(ascending=False))

HomePlanet
Europa    0.658846
Mars      0.523024
Earth     0.423946
Name: Transported, dtype: float64

Destination
55 Cancri e      0.610000
PSO J318.5-22    0.503769
TRAPPIST-1e      0.471175
Name: Transported, dtype: float64

In [10]:
train['AgeGroup'] = pd.cut(train['Age'], bins=[0, 12, 18, 30, 50, 100], labels=['Child', 'Teen', 'YoungAdult', 'Adult', 'Senior'])
print(train.groupby('AgeGroup', observed=True)['Transported'].mean())
print()
print(train.groupby('VIP')['Transported'].mean())

AgeGroup
Child         0.668790
Teen          0.537299
YoungAdult    0.468190
Adult         0.479432
Senior        0.484396
Name: Transported, dtype: float64

VIP
False    0.506332
True     0.381910
Name: Transported, dtype: float64

In [11]:
train['Group'] = train['PassengerId'].str.split('_').str[0]
group_size = train['Group'].value_counts()
train['GroupSize'] = train['Group'].map(group_size)
print(train.groupby('GroupSize')['Transported'].mean())

GroupSize
1    0.452445
2    0.538050
3    0.593137
4    0.640777
5    0.592453
6    0.614943
7    0.541126
8    0.394231
Name: Transported, dtype: float64

In [12]:
group_transported_std = train.groupby('Group')['Transported'].mean()
print(group_transported_std.value_counts(bins=[-0.01, 0.01, 0.5, 0.99, 1.01]))

(-0.011, 0.01]    2868
(0.99, 1.01]      2552
(0.01, 0.5]        565
(0.5, 0.99]        232
Name: count, dtype: int64